STATUS_CREATED = "CREATED"
STATUS_UPLOADING = "UPLOADING"
STATUS_QUEUED = "QUEUED"
STATUS_RUNNING = "RUNNING"
STATUS_SUCCEEDED = "SUCCEEDED"
STATUS_FAILED = "FAILED"
STATUS_CANCELED = "CANCELED"

STATUS_CHOICES = [
    (STATUS_CREATED, STATUS_CREATED),
    (STATUS_UPLOADING, STATUS_UPLOADING),
    (STATUS_QUEUED, STATUS_QUEUED),
    (STATUS_RUNNING, STATUS_RUNNING),
    (STATUS_SUCCEEDED, STATUS_SUCCEEDED),
    (STATUS_FAILED, STATUS_FAILED),
    (STATUS_CANCELED, STATUS_CANCELED),
]

STAGE_LOADING = "LOADING_FRAMES"
STAGE_WHITEBOARD_DETECTION = "WHITEBOARD_DETECTION"
STAGE_ALIGNMENT = "ALIGNMENT_AND_SEGMENTATION"
STAGE_BACKGROUND = "BACKGROUND_RECONSTRUCTION"
STAGE_INK = "INK_DETECTION"
STAGE_STROKE = "STROKE_COLOR_ESTIMATION"
STAGE_RENDER = "RENDER"
STAGE_SAVING = "SAVING"
STAGE_DONE = "DONE"
