# Generated by Django 5.0.10 on 2026-01-18 00:00

from django.db import migrations, models
import django.db.models.deletion
import digitization.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0002_room_janus_room_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitizationJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("CREATED", "CREATED"), ("UPLOADING", "UPLOADING"), ("QUEUED", "QUEUED"), ("RUNNING", "RUNNING"), ("SUCCEEDED", "SUCCEEDED"), ("FAILED", "FAILED"), ("CANCELED", "CANCELED")], default="CREATED", max_length=20)),
                ("stage", models.CharField(blank=True, default="", max_length=64)),
                ("expected_frames", models.IntegerField(default=9)),
                ("frame_width", models.IntegerField(blank=True, null=True)),
                ("frame_height", models.IntegerField(blank=True, null=True)),
                ("capture_source", models.CharField(blank=True, default="", max_length=64)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("processed_frames", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("result_image", models.FileField(blank=True, null=True, upload_to=digitization.models.job_result_upload_to)),
                ("background_image", models.FileField(blank=True, null=True, upload_to=digitization.models.job_result_upload_to)),
                ("debug_image", models.FileField(blank=True, null=True, upload_to=digitization.models.job_result_upload_to)),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="digitization_jobs", to="rooms.room")),
            ],
        ),
        migrations.CreateModel(
            name="DigitizationFrame",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("frame_index", models.IntegerField()),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("image", models.FileField(upload_to=digitization.models.frame_upload_to)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="frames", to="digitization.digitizationjob")),
            ],
            options={
                "ordering": ["frame_index"],
            },
        ),
        migrations.AddConstraint(
            model_name="digitizationframe",
            constraint=models.UniqueConstraint(fields=("job", "frame_index"), name="uniq_digitization_frame_index"),
        ),
    ]
