# Generated by Django 5.0.10 on 2026-01-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='janus_room_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
