# Generated by Django 5.0.10 on 2026-01-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = []
